[package]
name = "ffinder"
version = "0.1.0"
authors = ["speltriao"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
home = "0.5.3"
colored = "2"

[[bin]]
name = "ffinder"
path = "ffinder.rs"
